-- WatchRoulette schema
-- Run in Supabase: Project -> SQL Editor -> New query -> paste -> Run
-- Not needed until Module 1 (Repo) and Module 3 (Arena), but defined here
-- now since it's part of the spec, not something to improvise mid-module.

create table movie_repo (
  id bigint generated by default as identity primary key,
  title text not null,
  genres text[] default '{}',
  poster_path text,
  summary text,
  tmdb_id integer unique,
  watch_page_url text,
  added_by text,
  watched boolean default false,
  watched_at timestamp with time zone default null,
  spotlighted boolean default false,
  trailer_key text default null,
  created_at timestamp with time zone default now()
);
-- tmdb_id is unique so the same movie can't be added twice: a duplicate
-- would silently break the spin wheel's fairness math (same title occupying
-- two wedges). A client-side "already in the repo" check happens too, but
-- this constraint is the real backstop since two people could add the same
-- movie within the same second.

create table game_lobby (
  id text primary key,
  active_veto_user text default null,
  veto_used boolean default false,
  round_high_score integer default 0 check (round_high_score <= 200),
  round_high_score_holder text default null,
  round_number integer not null default 1,
  chosen_movie_id bigint references movie_repo(id) default null,
  spin_started_at timestamp with time zone default null,
  updated_at timestamp with time zone default now()
);
-- round_high_score is capped at 200 (was 45 before the Arena tweak below
-- added bonus cells + speed bursts, both of which raise the real ceiling
-- past the original ~43-hit math). Still a soft "block the type 999999 in
-- dev tools move" backstop, not full anti-cheat, and still deliberately not
-- derived precisely — see spec.md's "Arena tweak" section.
-- spin_started_at powers the synced wheel reveal: the spinner's client
-- decides the winner and writes it here immediately, every other client
-- detects the new timestamp on its next poll and plays the same fixed-
-- duration animation. Also used to disable the Spin button app-wide while
-- a spin is in flight (in progress = within the last 4 seconds).

-- One row per completed round, written by lobbyApi.resetRound() right
-- before it clears game_lobby for the next round (Module 5c). Turns
-- "which movie won the most spins" / "who's won the most rounds" into a
-- real query instead of something nobody could ever answer — game_lobby by
-- itself only ever remembers the current round's state.
create table round_history (
  id bigint generated by default as identity primary key,
  round_number integer not null,
  high_score integer not null,
  high_score_holder text,
  chosen_movie_id bigint references movie_repo(id),
  ended_at timestamp with time zone default now()
);
-- No pagination/retention design here on purpose — one row per movie
-- night means this would take years to become a real performance question
-- (see spec.md's Module 5c).

-- profiles (Module 7): the real-account identity layer, one row per
-- Supabase Auth user. display_name is set once by the person themselves
-- (the app's one-time "what should we call you" prompt); is_owner/revoked
-- are administrative flags only ever touched by this app's own server-side
-- admin endpoints (api/admin-invite.js, api/admin-revoke.js), never by a
-- client request — see the guard trigger below. revoked mirrors the real
-- Supabase-level ban api/admin-revoke.js sets; it enforces nothing on its
-- own, it only exists so the Manage Invites screen has something to query.
--
-- email is a deliberate duplication of auth.users.email, not the source of
-- truth for anything auth-related (Supabase's own auth.users row is that,
-- and always will be) — caught while actually building the Manage Invites
-- screen: auth.users isn't reachable from client code at all, even under
-- RLS, so without a copy here the invite list would have nothing to
-- display per person except a bare UUID. Written once by
-- api/admin-invite.js at invite time (it already has the email in hand);
-- never updated afterward, so it can't drift from what the account was
-- invited under.
create table profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  display_name text,
  is_owner boolean not null default false,
  revoked boolean not null default false,
  created_at timestamp with time zone default now()
);
-- Case-insensitive so "Vikram" and "vikram" can't both exist — matches how
-- someone would actually expect duplicate-name detection to work.
create unique index profiles_display_name_unique_ci on profiles (lower(display_name));

-- Case-insensitive for the same reason as display_name above — without
-- this, Foo@gmail.com and foo@gmail.com could become two different tracked
-- identities even though they're the same real account. Emails are
-- lowercased before every write and every lookup in api/admin-invite.js;
-- this index is the DB-level backstop, not the only thing normalizing them.
create unique index profiles_email_unique_ci on profiles (lower(email));

alter table profiles enable row level security;
create policy "authenticated can read all profiles" on profiles
  for select using (auth.role() = 'authenticated');
create policy "a user can set their own profile" on profiles
  for update using (auth.uid() = id);
-- No insert policy: rows only ever get created server-side (by
-- api/admin-invite.js at invite time, or the one-off owner bootstrap
-- script), both running with the service role, which bypasses RLS
-- entirely — there's no client-facing path that's meant to insert here.

-- Closes a gap caught in spec self-review: the update policy above only
-- restricts *which row* someone can update, not *which columns* — without
-- this trigger, any logged-in member could set is_owner/revoked on their
-- own row via a normal update. The service-role check is what still lets
-- api/admin-invite.js/api/admin-revoke.js themselves legitimately set them.
create or replace function reject_admin_column_changes() returns trigger as $$
begin
  if auth.role() = 'service_role' then
    return new;
  end if;

  if new.is_owner is distinct from old.is_owner
     or new.revoked is distinct from old.revoked then
    raise exception 'is_owner/revoked cannot be changed by a client update';
  end if;

  return new;
end;
$$ language plpgsql security definer;

create trigger profiles_guard_admin_columns
  before update on profiles
  for each row execute function reject_admin_column_changes();

insert into game_lobby (id) values ('current_session');

alter table movie_repo enable row level security;
alter table game_lobby enable row level security;
alter table round_history enable row level security;

-- Module 7: every policy below requires an authenticated session — this
-- replaces the original "anyone can ..." open policies (see the migration
-- block at the end of this file for what actually ran against the already-
-- live project, since these tables existed long before accounts did).
create policy "authenticated members can read movies" on movie_repo
  for select using (auth.role() = 'authenticated');
create policy "authenticated members can add movies" on movie_repo
  for insert with check (auth.role() = 'authenticated');
create policy "authenticated members can update movies" on movie_repo
  for update using (auth.role() = 'authenticated');
-- New in Module 7 — repoApi.removeMovie() has existed since Module 6 with
-- no matching delete policy at all, so it's been silently failing in
-- production (RLS denies by default with no policy present) since it
-- shipped. This is the fix.
create policy "authenticated members can delete movies" on movie_repo
  for delete using (auth.role() = 'authenticated');

create policy "authenticated members can read lobby state" on game_lobby
  for select using (auth.role() = 'authenticated');
create policy "authenticated members can update lobby state" on game_lobby
  for update using (auth.role() = 'authenticated');

create policy "authenticated members can read round history" on round_history
  for select using (auth.role() = 'authenticated');
create policy "authenticated members can log a completed round" on round_history
  for insert with check (auth.role() = 'authenticated');

-- Note: TMDB's /watch/providers endpoint does not return deep links into
-- Netflix/Prime/etc (blocked by its JustWatch data agreement). watch_page_url
-- stores TMDB's own /watch page link instead, which lists providers and
-- links onward from there.

-- spotlighted (added for Module 2): shared "boost this movie tonight" flag
-- behind the spin wheel's Spotlight feature (ADR 0001). Lives on movie_repo
-- rather than game_lobby since it's per-movie, not per-session, state.
--
-- movie_repo already existed live when this was added, so the CREATE TABLE
-- above (accurate for a fresh build) is not what actually ran against the
-- live project — this ALTER is:
-- alter table movie_repo add column if not exists spotlighted boolean default false;

-- round_number (added for Module 3): Arena's "one attempt per person per
-- round" is enforced client-side with no new table (per spec), but that
-- still needs *some* signal for a device to know a new round has actually
-- started, so it knows to clear its local "already played" flag. This
-- counter is that signal — incremented by lobbyApi.resetRound() alongside
-- the round_high_score/veto reset it already did.
--
-- Module 3 migration, same reasoning as spotlighted above:
-- alter table game_lobby add column if not exists round_number integer not null default 1;

-- round_high_score cap raised 45 -> 200 (Arena tweak: bonus cells + speed
-- bursts raise the real ceiling past the original ~43-hit math; see
-- spec.md). Postgres CHECK constraints can't be altered in place — the old
-- one has to be dropped and replaced:
-- alter table game_lobby drop constraint game_lobby_round_high_score_check;
-- alter table game_lobby add constraint game_lobby_round_high_score_check check (round_high_score <= 200);

-- trailer_key (added for Module 5a): a bare YouTube video id, not a full
-- URL — same "store it bare, build the link at render time" convention as
-- poster_path. Fetched once at add-time by api/tmdb-videos.js, not per
-- render. Null means "no trailer found," not "not fetched yet" — there's no
-- separate fetch-pending state, since the fetch always happens synchronously
-- as part of addMovie, before the insert.
--
-- Module 5a migration, same reasoning as spotlighted/round_number above:
-- alter table movie_repo add column if not exists trailer_key text default null;

-- round_high_score_holder (added for Module 5c): the attribution fix — the
-- existing `active_veto_user` gets silently cleared the moment a veto is
-- spent (by design, that column means "who currently holds the veto," not
-- "who set the record"), so there was no durable way to answer "who holds
-- the current high score" once a veto had been used. This column is set
-- alongside round_high_score in submitScoreIfHighest and is never touched
-- by useVeto — it's the source of truth resetRound reads from before
-- logging a completed round to round_history (see that table's own
-- comment above).
--
-- Module 5c migration, same reasoning as the others above:
-- alter table game_lobby add column if not exists round_high_score_holder text default null;
--
-- round_history is a new table for Module 5c, not an alter — see its own
-- CREATE TABLE above; ran directly against the live project the same way.

-- profiles (Module 7) is a new table, same as round_history above — ran
-- directly against the live project via its own CREATE TABLE block earlier
-- in this file, not an alter.
--
-- profiles_email_unique_ci (post-launch data-integrity fix): profiles
-- already existed live with 3 rows and no unique index on email at all when
-- this was added. Safe to add directly (no case-insensitive collisions
-- existed among those 3 real addresses), but worth a live ALTER, not a
-- fresh CREATE TABLE, since the table already existed:
-- create unique index profiles_email_unique_ci on profiles (lower(email));
--
-- movie_repo/game_lobby/round_history already existed live with the
-- original "anyone can ..." policies, so what actually ran against the
-- live project is a drop-and-recreate, not the plain CREATE POLICY blocks
-- above (which only read correctly for a fresh, from-scratch build):
--
-- drop policy "anyone can read movies" on movie_repo;
-- drop policy "anyone can add movies" on movie_repo;
-- drop policy "anyone can mark movies watched" on movie_repo;
-- create policy "authenticated members can read movies" on movie_repo
--   for select using (auth.role() = 'authenticated');
-- create policy "authenticated members can add movies" on movie_repo
--   for insert with check (auth.role() = 'authenticated');
-- create policy "authenticated members can update movies" on movie_repo
--   for update using (auth.role() = 'authenticated');
-- create policy "authenticated members can delete movies" on movie_repo
--   for delete using (auth.role() = 'authenticated');
--
-- drop policy "anyone can read lobby state" on game_lobby;
-- drop policy "anyone can update lobby state" on game_lobby;
-- create policy "authenticated members can read lobby state" on game_lobby
--   for select using (auth.role() = 'authenticated');
-- create policy "authenticated members can update lobby state" on game_lobby
--   for update using (auth.role() = 'authenticated');
--
-- drop policy "anyone can read round history" on round_history;
-- drop policy "anyone can log a completed round" on round_history;
-- create policy "authenticated members can read round history" on round_history
--   for select using (auth.role() = 'authenticated');
-- create policy "authenticated members can log a completed round" on round_history
--   for insert with check (auth.role() = 'authenticated');
