-- WatchRoulette schema
-- Run in Supabase: Project -> SQL Editor -> New query -> paste -> Run
-- Not needed until Module 1 (Repo) and Module 3 (Arena), but defined here
-- now since it's part of the spec, not something to improvise mid-module.

create table movie_repo (
  id bigint generated by default as identity primary key,
  title text not null,
  genres text[] default '{}',
  poster_path text,
  summary text,
  tmdb_id integer unique,
  watch_page_url text,
  added_by text,
  watched boolean default false,
  watched_at timestamp with time zone default null,
  spotlighted boolean default false,
  trailer_key text default null,
  created_at timestamp with time zone default now()
);
-- tmdb_id is unique so the same movie can't be added twice: a duplicate
-- would silently break the spin wheel's fairness math (same title occupying
-- two wedges). A client-side "already in the repo" check happens too, but
-- this constraint is the real backstop since two people could add the same
-- movie within the same second.

create table game_lobby (
  id text primary key,
  active_veto_user text default null,
  veto_used boolean default false,
  round_high_score integer default 0 check (round_high_score <= 200),
  round_high_score_holder text default null,
  round_number integer not null default 1,
  chosen_movie_id bigint references movie_repo(id) default null,
  spin_started_at timestamp with time zone default null,
  updated_at timestamp with time zone default now()
);
-- round_high_score is capped at 200 (was 45 before the Arena tweak below
-- added bonus cells + speed bursts, both of which raise the real ceiling
-- past the original ~43-hit math). Still a soft "block the type 999999 in
-- dev tools move" backstop, not full anti-cheat, and still deliberately not
-- derived precisely — see spec.md's "Arena tweak" section.
-- spin_started_at powers the synced wheel reveal: the spinner's client
-- decides the winner and writes it here immediately, every other client
-- detects the new timestamp on its next poll and plays the same fixed-
-- duration animation. Also used to disable the Spin button app-wide while
-- a spin is in flight (in progress = within the last 4 seconds).

-- One row per completed round, written by lobbyApi.resetRound() right
-- before it clears game_lobby for the next round (Module 5c). Turns
-- "which movie won the most spins" / "who's won the most rounds" into a
-- real query instead of something nobody could ever answer — game_lobby by
-- itself only ever remembers the current round's state.
create table round_history (
  id bigint generated by default as identity primary key,
  round_number integer not null,
  high_score integer not null,
  high_score_holder text,
  chosen_movie_id bigint references movie_repo(id),
  ended_at timestamp with time zone default now()
);
-- No pagination/retention design here on purpose — one row per movie
-- night means this would take years to become a real performance question
-- (see spec.md's Module 5c).

insert into game_lobby (id) values ('current_session');

alter table movie_repo enable row level security;
alter table game_lobby enable row level security;
alter table round_history enable row level security;

create policy "anyone can read movies" on movie_repo
  for select using (true);
create policy "anyone can add movies" on movie_repo
  for insert with check (true);
create policy "anyone can mark movies watched" on movie_repo
  for update using (true);

create policy "anyone can read lobby state" on game_lobby
  for select using (true);
create policy "anyone can update lobby state" on game_lobby
  for update using (true);

create policy "anyone can read round history" on round_history
  for select using (true);
create policy "anyone can log a completed round" on round_history
  for insert with check (true);

-- Note: TMDB's /watch/providers endpoint does not return deep links into
-- Netflix/Prime/etc (blocked by its JustWatch data agreement). watch_page_url
-- stores TMDB's own /watch page link instead, which lists providers and
-- links onward from there.

-- spotlighted (added for Module 2): shared "boost this movie tonight" flag
-- behind the spin wheel's Spotlight feature (ADR 0001). Lives on movie_repo
-- rather than game_lobby since it's per-movie, not per-session, state.
--
-- movie_repo already existed live when this was added, so the CREATE TABLE
-- above (accurate for a fresh build) is not what actually ran against the
-- live project — this ALTER is:
-- alter table movie_repo add column if not exists spotlighted boolean default false;

-- round_number (added for Module 3): Arena's "one attempt per person per
-- round" is enforced client-side with no new table (per spec), but that
-- still needs *some* signal for a device to know a new round has actually
-- started, so it knows to clear its local "already played" flag. This
-- counter is that signal — incremented by lobbyApi.resetRound() alongside
-- the round_high_score/veto reset it already did.
--
-- Module 3 migration, same reasoning as spotlighted above:
-- alter table game_lobby add column if not exists round_number integer not null default 1;

-- round_high_score cap raised 45 -> 200 (Arena tweak: bonus cells + speed
-- bursts raise the real ceiling past the original ~43-hit math; see
-- spec.md). Postgres CHECK constraints can't be altered in place — the old
-- one has to be dropped and replaced:
-- alter table game_lobby drop constraint game_lobby_round_high_score_check;
-- alter table game_lobby add constraint game_lobby_round_high_score_check check (round_high_score <= 200);

-- trailer_key (added for Module 5a): a bare YouTube video id, not a full
-- URL — same "store it bare, build the link at render time" convention as
-- poster_path. Fetched once at add-time by api/tmdb-videos.js, not per
-- render. Null means "no trailer found," not "not fetched yet" — there's no
-- separate fetch-pending state, since the fetch always happens synchronously
-- as part of addMovie, before the insert.
--
-- Module 5a migration, same reasoning as spotlighted/round_number above:
-- alter table movie_repo add column if not exists trailer_key text default null;

-- round_high_score_holder (added for Module 5c): the attribution fix — the
-- existing `active_veto_user` gets silently cleared the moment a veto is
-- spent (by design, that column means "who currently holds the veto," not
-- "who set the record"), so there was no durable way to answer "who holds
-- the current high score" once a veto had been used. This column is set
-- alongside round_high_score in submitScoreIfHighest and is never touched
-- by useVeto — it's the source of truth resetRound reads from before
-- logging a completed round to round_history (see that table's own
-- comment above).
--
-- Module 5c migration, same reasoning as the others above:
-- alter table game_lobby add column if not exists round_high_score_holder text default null;
--
-- round_history is a new table for Module 5c, not an alter — see its own
-- CREATE TABLE above; ran directly against the live project the same way.
