import { supabase } from './supabaseClient'

// game_lobby read/write. Placed in shared/ rather than under one feature —
// the spec's folder listing shows it living under `arena/` (Module 3), but
// the Decision Engine (Module 2) needs to read and write this same row
// first (chosen_movie_id, spin_started_at, veto fields), so it's a shared
// data-access layer from the start rather than something Module 2 reaches
// across features to use.
const LOBBY_ROW_ID = 'current_session'

export async function fetchLobby() {
  const { data, error } = await supabase
    .from('game_lobby')
    .select('*')
    .eq('id', LOBBY_ROW_ID)
    .single()

  if (error) throw error
  return data
}

// Writes the winner immediately, before the spinner's own animation even
// finishes (ADR 0002) — every other client picks this up on its next poll
// and plays the same fixed-duration reveal locally.
//
// spinStartedAt is generated by the CALLER, not here — the spinner's own
// component needs to know the exact timestamp it just wrote so it can mark
// it "already seen" locally and animate immediately, without waiting on a
// round trip to confirm what it already knows.
export async function startSpin(chosenMovieId, spinStartedAt) {
  const { error } = await supabase
    .from('game_lobby')
    .update({ chosen_movie_id: chosenMovieId, spin_started_at: spinStartedAt })
    .eq('id', LOBBY_ROW_ID)

  if (error) throw error
}

// Spends the veto: writes the re-spin result and marks the veto used in one
// update, so there's never a moment where veto_used is true but the pick
// hasn't actually changed (or vice versa). Same spinStartedAt-from-caller
// reasoning as startSpin above.
export async function useVeto(newChosenMovieId, spinStartedAt) {
  const { error } = await supabase
    .from('game_lobby')
    .update({
      chosen_movie_id: newChosenMovieId,
      spin_started_at: spinStartedAt,
      veto_used: true,
      active_veto_user: null,
    })
    .eq('id', LOBBY_ROW_ID)

  if (error) throw error
}

// "New round" per spec's Reset bullet. Now also logs the round that just
// ended to round_history (Module 5c) before clearing game_lobby for the
// next one — takes the whole current lobby row, not just its round_number,
// since the history row needs the score/holder/movie that round actually
// ended with, not just the counter.
//
// Incrementing round_number here is what lets every device's Arena tell "a
// new round started" apart from "nothing happened yet," without a new
// table for that specific signal (Module 3's one-attempt-per-round gating
// depends on this).
export async function resetRound(lobby) {
  const { error: historyError } = await supabase.from('round_history').insert({
    round_number: lobby.round_number,
    high_score: lobby.round_high_score,
    high_score_holder: lobby.round_high_score_holder,
    chosen_movie_id: lobby.chosen_movie_id,
  })
  if (historyError) throw historyError

  const { error } = await supabase
    .from('game_lobby')
    .update({
      round_high_score: 0,
      round_high_score_holder: null,
      veto_used: false,
      active_veto_user: null,
      round_number: lobby.round_number + 1,
    })
    .eq('id', LOBBY_ROW_ID)

  if (error) throw error
}

// Submits an Arena score, only actually writing it if it beats the current
// high score — the `.lt` filter makes this a conditional update on the
// database side, so two people finishing their round moments apart can't
// race each other into overwriting a genuinely higher score with a lower
// one. Silent no-op (not an error) if the score doesn't beat the record;
// callers can tell whether they won by re-fetching the lobby afterward.
//
// Sets both active_veto_user (who currently holds the veto — cleared the
// moment it's spent, see useVeto) and round_high_score_holder (who set the
// record — durable, never cleared by useVeto, read by resetRound above and
// by the Module 5c stats page as "reigning Arena champion").
export async function submitScoreIfHighest(name, score) {
  const { error } = await supabase
    .from('game_lobby')
    .update({ round_high_score: score, round_high_score_holder: name, active_veto_user: name })
    .eq('id', LOBBY_ROW_ID)
    .lt('round_high_score', score)

  if (error) throw error
}

// Spin-lock derivation, per spec: "in progress = within the last 4 seconds,
// no new schema." Pure function so it's unit-testable without a network
// call or fake clock — the caller passes `now`.
export function isSpinInProgress(lobby, now = Date.now()) {
  if (!lobby?.spin_started_at) return false
  return now - new Date(lobby.spin_started_at).getTime() < 4000
}

// Module 5c's stats page reads the full round-by-round record, oldest
// first — ascending order matches how a person would actually read "the
// history of this app," not a network/DB implementation detail.
export async function fetchRoundHistory() {
  const { data, error } = await supabase
    .from('round_history')
    .select('*')
    .order('ended_at', { ascending: true })

  if (error) throw error
  return data
}
